name: CI
on: [ push, pull_request, workflow_dispatch ]
env:
  DOTNET_NOLOGO: 1
jobs:
  Build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build
        run: dotnet build
        
      - name: Test
        run: dotnet test --no-build -v normal --logger trx
        
      - name: Publish unit test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit Test Report
          path: '**/*.trx'
          reporter: dotnet-trx
