name: CI
on: [ push, pull_request, workflow_dispatch ]
jobs:
  Build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: dotnet build
        
      - name: Test
        run: dotnet test --no-build -v normal --logger trx
        
      - name: Publish unit test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit Test Report
          path: '**/*.trx'
          reporter: dotnet-trx
